package com.score.bean;

import java.io.Serializable;

public class TScore implements Serializable {

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * t_score.score_id
     *
     * @mbggenerated
     */
    private Integer scoreId;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * t_score.score_value
     *
     * @mbggenerated
     */
    private Integer scoreValue;

    private Integer subjectId;
    private String subjectName;

    private String subjectType;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * t_score.student_id
     *
     * @mbggenerated
     */
    private Integer studentId;

    private String studentName;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database table
     * t_score
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    public Integer getSubjectId() {
        return subjectId;
    }

    public void setSubjectId(Integer subjectId) {
        this.subjectId = subjectId;
    }

    public String getSubjectName() {
        return subjectName;
    }

    public void setSubjectName(String subjectName) {
        this.subjectName = subjectName;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database
     * column t_score.score_id
     *
     * @return the value of t_score.score_id
     * @mbggenerated
     */
    public Integer getScoreId() {
        return scoreId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database
     * column t_score.score_id
     *
     * @param scoreId the value for t_score.score_id
     * @mbggenerated
     */
    public void setScoreId(Integer scoreId) {
        this.scoreId = scoreId;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database
     * column t_score.score_value
     *
     * @return the value of t_score.score_value
     * @mbggenerated
     */
    public Integer getScoreValue() {
        return scoreValue;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database
     * column t_score.score_value
     *
     * @param scoreValue the value for t_score.score_value
     * @mbggenerated
     */
    public void setScoreValue(Integer scoreValue) {
        this.scoreValue = scoreValue;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database
     * column t_score.student_id
     *
     * @return the value of t_score.student_id
     * @mbggenerated
     */
    public Integer getStudentId() {
        return studentId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database
     * column t_score.student_id
     *
     * @param studentId the value for t_score.student_id
     * @mbggenerated
     */
    public void setStudentId(Integer studentId) {
        this.studentId = studentId;
    }

    public String getStudentName() {
        return studentName;
    }

    public void setStudentName(String studentName) {
        this.studentName = studentName;
    }

    public String getSubjectType() {
        return subjectType;
    }

    public void setSubjectType(String subjectType) {
        this.subjectType = subjectType;
    }
}